In [300]:
import pandas as pd
from scipy.stats import zscore

In [301]:
df = pd.read_csv('data.csv')

Questão 2b)

É possível notar aqui que a sétima observação é um outlier dado que o valor "450" é bem distante da média de duração, puxando para um valor muito alto.

In [302]:
zscore(df['Duration'])

0    -0.122395
1    -0.122395
2    -0.122395
3    -0.339987
4    -0.339987
5    -0.122395
6    -0.122395
7     5.534982
8    -0.557578
9    -0.122395
10   -0.122395
11   -0.122395
12   -0.122395
13   -0.122395
14   -0.122395
15   -0.122395
16   -0.122395
17   -0.122395
18   -0.339987
19   -0.122395
20   -0.339987
21   -0.122395
22   -0.339987
23   -0.122395
24   -0.339987
25   -0.122395
26   -0.122395
27   -0.122395
28   -0.122395
29   -0.122395
30   -0.122395
31   -0.122395
Name: Duration, dtype: float64

Aqui, faremos a substituição da duração que está com um valor extremo para a média, de forma que não altera o nosso resultado pois não altera o resultado da nossa análise.

In [303]:
mean_durations = df["Duration"].mean()

df.loc[7, "Duration"] = int(mean_durations)

Queremos preencher as calorias, para isto, utilizaremos a média em lugares que os valores são vazio.

In [304]:
median_calories = df["Calories"].median()

df["Calories"] = df["Calories"].fillna(median_calories)

Assim como as datas estão mal formatadas e principalmente com valores numéricos (erratas), queremos fazer esse tratamento transformando para data. O que for transformado e falhar, isto é, um dado que não é uma data, eliminaremos a linha.

In [305]:
df['Date'] = pd.to_datetime(df['Date'], format='mixed')

df.dropna(subset=['Date'], inplace = True)

Eliminaremos dados duplicados pois não será útil para o nosso dataset final manter as mesmas instâncias.

In [306]:
df.drop_duplicates(inplace = True)

df

    Duration       Date  Pulse  Maxpulse  Calories
0         60 2020-12-01    110       130     409.1
1         60 2020-12-02    117       145     479.0
2         60 2020-12-03    103       135     340.0
3         45 2020-12-04    109       175     282.4
4         45 2020-12-05    117       148     406.0
5         60 2020-12-06    102       127     300.0
6         60 2020-12-07    110       136     374.0
7         68 2020-12-08    104       134     253.3
8         30 2020-12-09    109       133     195.1
9         60 2020-12-10     98       124     269.0
10        60 2020-12-11    103       147     329.3
11        60 2020-12-12    100       120     250.7
13        60 2020-12-13    106       128     345.3
14        60 2020-12-14    104       132     379.3
15        60 2020-12-15     98       123     275.0
16        60 2020-12-16     98       120     215.2
17        60 2020-12-17    100       120     300.0
18        45 2020-12-18     90       112     291.2
19        60 2020-12-19    103       123     323.0
20        45 2020-12-20     97       125     243.0
21        60 2020-12-21    108       131     364.2
23        60 2020-12-23    130       101     300.0
24        45 2020-12-24    105       132     246.0
25        60 2020-12-25    102       126     334.5
26        60 2020-12-26    100       120     250.0
27        60 2020-12-27     92       118     241.0
28        60 2020-12-28    103       132     291.2
29        60 2020-12-29    100       132     280.0
30        60 2020-12-30    102       129     380.3
31        60 2020-12-31     92       115     243.0

Questão 3)

Sabemos que ao calcular o z-score, temos que se $z > 3$ ou $z < -3$, então, os valores estão a mais de 3 desvios padrões da média (para cima ou para baixo), pois a fórmula:

$z = \frac{x - \mu}{\sigma}$

Aqui na coluna "Pulse", a linha 23 tem um z-score maior do que 3, o que indica que é um bom indício para considerar outlier.

In [307]:
zscore(df['Pulse'])

0     0.792494
1     1.677728
2    -0.092739
3     0.666033
4     1.677728
5    -0.219201
6     0.792494
7     0.033723
8     0.666033
9    -0.725048
10   -0.092739
11   -0.472124
13    0.286647
14    0.033723
15   -0.725048
16   -0.725048
17   -0.472124
18   -1.736743
19   -0.092739
20   -0.851510
21    0.539571
23    3.321732
24    0.160185
25   -0.219201
26   -0.472124
27   -1.483819
28   -0.092739
29   -0.472124
30   -0.219201
31   -1.483819
Name: Pulse, dtype: float64

Questão 3)

Aqui na coluna "Maxpulse", a linha 3 tem um z-score maior do que 3, o que indica que é um bom indício para considerar outlier.

In [308]:
zscore(df['Maxpulse'])

0     0.069267
1     1.223717
2     0.454084
3     3.532616
4     1.454607
5    -0.161623
6     0.531047
7     0.377120
8     0.300157
9    -0.392513
10    1.377643
11   -0.700366
13   -0.084660
14    0.223194
15   -0.469476
16   -0.700366
17   -0.700366
18   -1.316073
19   -0.469476
20   -0.315550
21    0.146230
23   -2.162669
24    0.223194
25   -0.238586
26   -0.700366
27   -0.854293
28    0.223194
29    0.223194
30   -0.007696
31   -1.085183
Name: Maxpulse, dtype: float64

Questão 3)

Não há indício de outlier em calorias por conta dos critérios estabelecidos anteriormente.

In [309]:
zscore(df['Calories'])

0     1.603647
1     2.694453
2     0.525325
3    -0.373538
4     1.555271
5    -0.098885
6     1.055903
7    -0.827650
8    -1.735875
9    -0.582648
10    0.358348
11   -0.868224
13    0.608032
14    1.138611
15   -0.489016
16   -1.422210
17   -0.098885
18   -0.236211
19    0.260035
20   -0.988384
21    0.902971
23   -0.098885
24   -0.941568
25    0.439496
26   -0.879147
27   -1.019595
28   -0.236211
29   -0.410990
30    1.154216
31   -0.988384
Name: Calories, dtype: float64

In [310]:
z_scores = df[['Pulse', 'Maxpulse', 'Calories']].apply(zscore)

combinacoes = (z_scores < 3).all(axis=1) & (z_scores > -3).all(axis=1)

df = df[combinacoes]

df

    Duration       Date  Pulse  Maxpulse  Calories
0         60 2020-12-01    110       130     409.1
1         60 2020-12-02    117       145     479.0
2         60 2020-12-03    103       135     340.0
4         45 2020-12-05    117       148     406.0
5         60 2020-12-06    102       127     300.0
6         60 2020-12-07    110       136     374.0
7         68 2020-12-08    104       134     253.3
8         30 2020-12-09    109       133     195.1
9         60 2020-12-10     98       124     269.0
10        60 2020-12-11    103       147     329.3
11        60 2020-12-12    100       120     250.7
13        60 2020-12-13    106       128     345.3
14        60 2020-12-14    104       132     379.3
15        60 2020-12-15     98       123     275.0
16        60 2020-12-16     98       120     215.2
17        60 2020-12-17    100       120     300.0
18        45 2020-12-18     90       112     291.2
19        60 2020-12-19    103       123     323.0
20        45 2020-12-20     97       125     243.0
21        60 2020-12-21    108       131     364.2
24        45 2020-12-24    105       132     246.0
25        60 2020-12-25    102       126     334.5
26        60 2020-12-26    100       120     250.0
27        60 2020-12-27     92       118     241.0
28        60 2020-12-28    103       132     291.2
29        60 2020-12-29    100       132     280.0
30        60 2020-12-30    102       129     380.3
31        60 2020-12-31     92       115     243.0